syntax = "proto3";

package dhrmaes.storage.protobuf.filesystem.file.v1;

import "Protos/FileSystem/File/file_v1.proto";

option csharp_namespace = "DhrMaes.Storage.Protobuf.FileSystem.File.v1";

message OpenReadRequest {
  string file_name = 1;
}

message OpenReadResponse{
  oneof payload {
    dhrmaes.storage.protobuf.filesystem.file.v1.FileInfo info = 1;    // first message: metadata
    dhrmaes.storage.protobuf.filesystem.file.v1.FileChunk chunk = 2;  // subsequent messages: binary data
  }
}
