syntax = "proto3";

package dhrmaes.storage.protobuf.configuration.providers.v1;

import "Protos/Configuration/Providers.proto";

option csharp_namespace = "DhrMaes.Storage.Protobuf.Configuration.Providers.v1";

service ProviderService {
    rpc AddProvider (AddProviderRequest) returns (AddProviderResponse);
    rpc AuthenticateProvider(AuthenticateProviderRequest) returns (AuthenticateProviderResponse);
    rpc RemoveProvider (RemoveProviderRequest) returns (RemoveProviderResponse);
    rpc ListProviders (ListProvidersRequest) returns (ListProvidersResponse);
    rpc GetPlugins(GetPluginsRequest) returns (GetPluginsResponse);
}

message AddProviderRequest {
    ProviderConfig provider = 1;
}

message AddProviderResponse {
    string identifier = 1;
    bool needs_authentication = 2;
}

message AddProviderRequest {
    ProviderConfig provider = 1;
}

message AddProviderResponse {
    string identifier = 1;
}

message ListProvidersRequest {
}

message ListProvidersResponse {
    repeated Provider providers = 1;
}

message RemoveProviderRequest {
    string identifier = 1;
}

message RemoveProviderResponse {
}

message GetPluginsRequest {
}

message GetPluginsResponse {
    repeated ProviderConfig plugins = 1;
}