syntax = "proto3";

package dhrmaes.storage.protobuf.configuration.providers.v1;

import "Protos/Configuration/Providers.proto";

option csharp_namespace = "DhrMaes.Storage.Protobuf.Configuration.Providers.v1";

service ProviderService {
    rpc AddProvider (AddProviderRequest) returns (AddProviderResponse);
    rpc RemoveProvider (RemoveProviderRequest) returns (RemoveProviderResponse);
    rpc ListProviders (ListProvidersRequest) returns (ListProvidersResponse);
    rpc GetInstalledProviders(GetInstalledProvidersRequest) returns (GetInstalledProvidersResponse);
}

message AddProviderRequest {
    ProviderConfig provider = 1;
}

message AddProviderResponse {
    string identifier = 1;
}

message ListProvidersRequest {
}

message ListProvidersResponse {
    repeated Provider providers = 1;
}

message RemoveProviderRequest {
    string identifier = 1;
}

message RemoveProviderResponse {
}

message GetInstalledProvidersRequest {
}

message GetInstalledProvidersResponse {
    repeated ProviderConfig providers = 1;
}