syntax = "proto3";

package dhrmaes.storage.protobuf.configuration.providers.v1;

option csharp_namespace = "DhrMaes.Storage.Protobuf.Configuration.Providers.v1";

message Provider {
    string type = 1;
    string identifier = 2;
}

message ProviderConfig {
  string name = 1;  
  repeated ProviderConfigProperty properties = 2;
}

message ProviderConfigProperty {
  string name = 1;
  string description = 2;
  ProviderConfigPropertyType type = 3;
  oneof value {
    string string_value = 4;
    int32 int_value = 5;
    bool bool_value = 6;
    double double_value = 7;
  }
}

enum ProviderConfigPropertyType {
    PROVIDERCONFIGPROPERTYTYPE_UNSPECIFIED = 0;
    PROVIDERCONFIGPROPERTYTYPE_STRING = 1;
    PROVIDERCONFIGPROPERTYTYPE_INT = 2;
    PROVIDERCONFIGPROPERTYTYPE_BOOL = 3;
    PROVIDERCONFIGPROPERTYTYPE_DOUBLE = 4;
}