<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<RootNamespace>DhrMaes.Storage</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
	  <Protobuf Include="Protos\FileSystem\Directory\remove_directory_v1.proto" />
	  <Protobuf Include="Protos\FileSystem\Directory\make_directory_v1.proto" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Google.Protobuf" Version="3.32.1" />
		<PackageReference Include="Grpc.Core" Version="2.46.6" />
		<PackageReference Include="Grpc.Tools" Version="2.72.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<Protobuf Include="Protos\FileSystem\StorageService.proto" GrpcServices="Both" />
		<Protobuf Include="Protos\Structure.proto" GrpcServices="None" />
		<Protobuf Include="Protos\FileSystem\Directory\list_directory_v1.proto" GrpcServices="Both" />
		<Protobuf Include="Protos\FileSystem\Directory\make_directory_v1.proto" GrpcServices="Both" />
		<Protobuf Include="Protos\FileSystem\Directory\remove_directory_v1.proto" GrpcServices="Both" />
		<Protobuf Include="Protos\Configuration\Providers.proto" GrpcServices="None" />
		<Protobuf Include="Protos\Configuration\ProviderService.proto" GrpcServices="Both" />
	</ItemGroup>

</Project>