<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Storage.Plugin.Contracts\Storage.Plugin.Contracts.csproj" />
    <ProjectReference Include="..\Storage.Plugin.Loader\Storage.Plugin.Loader.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
