<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<RootNamespace>DhrMaes.Storage.Core</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="$(MSBuildProjectName).UnitTests" />
		<InternalsVisibleTo Include="Storage.Console" />
	</ItemGroup>
</Project>
