<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<RootNamespace>DhrMaes.Storage.Provider.FileSystem</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Storage.Core\Storage.Core.csproj" />
	</ItemGroup>

</Project>
