syntax = "proto3";

package dhrmaes.storage.protobuf.filesystem.v1;

import "Protos/FileSystem/Directory/list_directory_v1.proto";
import "Protos/FileSystem/Directory/make_directory_v1.proto";
import "Protos/FileSystem/Directory/remove_directory_v1.proto";

option csharp_namespace = "DhrMaes.Storage.Protobuf.FileSystem.v1";

service StorageService {
  rpc ListDirectory (dhrmaes.storage.protobuf.filesystem.directory.v1.ListDirectoryRequest) returns (dhrmaes.storage.protobuf.filesystem.directory.v1.ListDirectoryResponse);
  rpc MakeDirectory (dhrmaes.storage.protobuf.filesystem.directory.v1.MakeDirectoryRequest) returns (dhrmaes.storage.protobuf.filesystem.directory.v1.MakeDirectoryResponse);
  rpc RemoveDirectory (dhrmaes.storage.protobuf.filesystem.directory.v1.RemoveDirectoryRequest) returns (dhrmaes.storage.protobuf.filesystem.directory.v1.RemoveDirectoryResponse);
}
